# Home Assistant integration (MQTT discovery)
homeassistant: false

# allow new devices to join
permit_join: true

# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL
  # server: 'mqtt://localhost'
  server: 'mqtt://192.168.1.42'
  # MQTT server authentication, uncomment if required:
  user: LOGIN
  password: MOT_PASSE

# Serial settings
serial:
  # Location of CC2531 USB sniffer
  port: /dev/ttyACM0
frontend: true
frontend:
  port:8088
  host: 0.0.0.0
 
