# Loads default set of integrations. Do not remove.
default_config:
mobile_app:

pyscript:
  allow_all_imports: true
  hass_is_global: true

notify:
  - name: "email"
    platform: smtp
    server: "smtp.orange.fr"
    port: 587
    timeout: 15
    encryption: starttls
    username: "michel.gravier@orange.fr"
    password: "Eveline_Idem_1945_truffiere_24"
    sender: "michel.gravier@orange.fr"
    recipient: 
      - "michel.gravier@mailo.com"
    sender_name: "GRAVIER Michel" 
    debug: true

  - name: monitor
    platform: rest
    resource: http://192.168.1.9/monitor

input_boolean:
  essai:
    name: "switch_binaire"
    icon: mdi:gesture-tap
   
  notify_home:
    name: Notify when someone arrives home
    icon: mdi:car    
logger:
  default: info
  logs:
    homeassistant.components.mqtt: debug    
    
template:
  -  sensor:
       -  name: "liste_var"
          unique_id : listvar001
          state: >
            {% for input_text in states.input_text %}
            {{input_text.entity_id ~ ":" ~ input_text.state ~ ", " }}
            {% endfor %}

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate
api:
automation: !include automations.yaml

#      
script: !include scripts.yaml
scene: !include scenes.yaml
group: !include groups.yaml
mqtt: !include_dir_merge_named mqtt
python_script: !include_dir_merge_named python_script/

   
http:
  cors_allowed_origins:
    -  http://192.168.1.9
  use_x_forwarded_for: true
  trusted_proxies:
    -  192.168.1.0/24

rest:
  - resource: "http://192.168.1.9/monitor/api/json.php?app=fichier"
    scan_interval: 5
    sensor:
      - name: "Report"
        unique_id: connect_to_monitor_1
        value_template: "report={{ value_json[0]['idx'] }}"

rest_command:
  monitor_1:
    url: "http://192.168.1.9/monitor/api/json.php?app=messages&name=message1&contenu={{svalue}}&maj=1=0"
   
